name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ubuntu-latest"

      - name: Run tests
        run: cargo test --verbose

  build:
    needs: test
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ matrix.os }}"

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4.6.1
        with:
          name: qazer-git
          path: ./target/release/qazer*

